# templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-postgresql.fullname" . }}
  labels:
    app: {{ include "my-postgresql.name" . }}
    chart: {{ include "my-postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      nodePort: {{ .Values.service.nodePort | default nil }}
  selector:
    app: {{ include "my-postgresql.name" . }}
    release: {{ .Release.Name }}
